// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_xIYTntdvcwTfz87HNOFhK7IiaE9VbB0',
    appId: '1:114265146280:web:9a2a381fb8c127dbf3939d',
    messagingSenderId: '114265146280',
    projectId: 'fkmarket-83c01',
    authDomain: 'fkmarket-83c01.firebaseapp.com',
    storageBucket: 'fkmarket-83c01.firebasestorage.app',
    measurementId: 'G-P9MKN4TJGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-9OLMkBJgJvjxYUyHm_xalr7bNETG4RE',
    appId: '1:114265146280:android:18bbcb5165817a44f3939d',
    messagingSenderId: '114265146280',
    projectId: 'fkmarket-83c01',
    storageBucket: 'fkmarket-83c01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWIcGiSbiEK5dUUApaIjKnRA9bZpMztNc',
    appId: '1:114265146280:ios:324351a5068f233cf3939d',
    messagingSenderId: '114265146280',
    projectId: 'fkmarket-83c01',
    storageBucket: 'fkmarket-83c01.firebasestorage.app',
    iosBundleId: 'com.example.fadaAlhalijWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWIcGiSbiEK5dUUApaIjKnRA9bZpMztNc',
    appId: '1:114265146280:ios:324351a5068f233cf3939d',
    messagingSenderId: '114265146280',
    projectId: 'fkmarket-83c01',
    storageBucket: 'fkmarket-83c01.firebasestorage.app',
    iosBundleId: 'com.example.fadaAlhalijWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_xIYTntdvcwTfz87HNOFhK7IiaE9VbB0',
    appId: '1:114265146280:web:f643b69c426c5e36f3939d',
    messagingSenderId: '114265146280',
    projectId: 'fkmarket-83c01',
    authDomain: 'fkmarket-83c01.firebaseapp.com',
    storageBucket: 'fkmarket-83c01.firebasestorage.app',
    measurementId: 'G-05TS024FQW',
  );
}
